use axum::{http::header, response::IntoResponse};

// Generated by admin-ui/src/build.mjs; this is the sole page source used by
// the service at runtime.
const INDEX: &str = include_str!("../admin-ui/dist/index.html");
const APP_JS: &str = include_str!("../admin-ui/dist/app.js");
const STYLES_CSS: &str = include_str!("../admin-ui/dist/styles.css");
const CSP: &str = "default-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'";

pub async fn index() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, "text/html; charset=utf-8"),
            (header::CONTENT_SECURITY_POLICY, CSP),
            (header::X_CONTENT_TYPE_OPTIONS, "nosniff"),
        ],
        INDEX,
    )
}

pub async fn app_js() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, "text/javascript; charset=utf-8"),
            (header::CONTENT_SECURITY_POLICY, CSP),
            (header::X_CONTENT_TYPE_OPTIONS, "nosniff"),
        ],
        APP_JS,
    )
}

pub async fn styles_css() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, "text/css; charset=utf-8"),
            (header::CONTENT_SECURITY_POLICY, CSP),
            (header::X_CONTENT_TYPE_OPTIONS, "nosniff"),
        ],
        STYLES_CSS,
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn embedded_admin_page_is_the_generated_frontend() {
        let page = super::INDEX;
        assert!(page.contains("/admin/app.js"));
        assert!(page.contains("/admin/styles.css"));
        assert!(!page.contains("<style>"));
        assert!(!page.contains("<script type=\"module\">"));
        assert!(!page.contains("sessionStorage"));
        assert!(super::APP_JS.contains("csrfToken"));
    }
}
