use axum::{http::header, response::IntoResponse};

// Generated by admin-ui/src/build.mjs; this is the sole page source used by
// the service at runtime.
const INDEX: &str = include_str!("../admin-ui/dist/index.html");

pub async fn index() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, "text/html; charset=utf-8")], INDEX)
}

#[cfg(test)]
mod tests {
    #[test]
    fn embedded_admin_page_is_the_generated_frontend() {
        let page = super::INDEX;
        assert!(page.contains("/admin/auth/login"));
        assert!(page.contains("csrfToken"));
        assert!(!page.contains("sessionStorage"));
    }
}
